name: CI Enhancement

on:
  pull_request:
    branches:
      - develop

jobs:
  codeReview:
    name: Discord notification
    env:
      DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
    uses: Ilshidur/action-discord@master
    with:
      args: 'O projeto {{ EVENT_PAYLOAD.repository.full_name }} tem um PR aberto para revisão.'
