name: CI Enhancement Notification

on:
  pull_request:
    branches:
      - develop

jobs:
  notificate-code-review:
    runs-on: ubuntu-latest

    name: Alert Notification Code Review
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Send notification to Discord Channel
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        uses: Ilshidur/action-discord@master
        with:
          args: 'Novos commits em: https://github.com/${{ github.repository }}/pull/${{ github.event.number }} :eyes: :mag_right:'
