name: CI Enhancement Notification

on:
  pull_request:
    branches: [develop]

  push:
    branches: [main]

jobs:
  notificate-code-review:
    runs-on: ubuntu-latest

    name: Alert Notification Code Review
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Send notification build code for production
        if: ${{ github.ref == 'refs/heads/main' }}
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        uses: Ilshidur/action-discord@master
        with:
          args: 'Taca-lhe pau em produção: https://github.com/${{ github.repository }}/tree/main :sunglasses: :fire:'

      - name: Echo variable REF
        env:
          REF: 'refs/pull/${{ github.event.number }}/merge'
        run: echo "REF=$REF" >> $GITHUB_ENV

      - name: Send notification new commits in PR -> develop
        if: ${{ github.ref == env.REF }}
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        uses: Ilshidur/action-discord@master
        with:
          args: 'Novos commits em: https://github.com/${{ github.repository }}/pull/${{ github.event.number }} :eyes: :mag_right:'
