name: CI

on:
  push:
    branches:
      - main
      - develop
      - staging/*.*.*

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.15.1]

    steps:
      - uses: actions/checkout@v2
      - name: Using Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: yarn --frozen-lockfile

      - name: Runnning tests
        run: yarn test
        env:
          CI: true
